# This is a basic workflow to help you get started with Actions

name: build

on:
   workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2

      - name: Run Open Orbis Toolchain
        uses: OpenOrbis/toolchain-action@main
        with:
          version: latest
          command: cd hello_world; make; PkgTool.Core pkg_build pkg/pkg.gp4 .

      - name: Upload Artifact
        uses: actions/upload-artifact@v2
        with:
          name: IV0000-BREW00083_00-HELLOWORLD000000.pkg
          path: hello_world/IV0000-BREW00083_00-HELLOWORLD000000.pkg
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
